/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.kwawingu.payments;

public class GoogleHttpClient {
    public int getGoogleStatusCode() {

        return 0;
    }
}
