/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.kwawingu.payments;

import java.io.IOException;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;

public class GoogleHttpClient {
    public int getGoogleStatusCode() throws IOException {
        URL url = new URL("https://google.com");
        HttpURLConnection connection = (HttpURLConnection) url.openConnection();
        connection.setRequestMethod("GET");

        int statusCode = connection.getResponseCode();
        connection.disconnect();

        return statusCode;
    }
}
